name: 'Get and cache dependencies'
description: 'Get the dependencies via npm and cache them'
inputs:
  enable-cache:
    description: 'Controls cache enable behavior'
    required: false
    default: 'true'
outputs:
  enable-cache:
    description: 'Show controls cache enable behavior'
    value: ${{ steps.install.outputs.enable-cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.enable-cache == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.enable-cache != 'true'
      run: |
       npm ci
       echo "enable-cache=${{ inputs.enable-cache }}" >> $GITHUB_OUTPUT
      shell: bash